enableSodiumMenu = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "FAST"
leavesCullingDepth = 2
includeMangroveRoots = true
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
universal_ores = true
creatures_of_the_snow = true
mcwdoors = true
mcwfences = true
farmersdelight = true
supplementaries = true
enchanted-vertical-slabs = true
overweight_farming = true
mcwwindows = true
rotten = true
endrem = true
geodes = true
eldritch_mobs = true
missingwilds = true
seasons = true
customportals = true
another_furniture = true
xps = true
twigs = true
ecologics = true
architects_palette = true
minecraft = true
animal_feeding_trough = true
lootr = true
blossom = true
enhancedcelestials = true
mcwbridges = true
numismatic-overhaul = true
byg = true
mcwtrpdoors = true
moisturization = true
display_case = true
adventurez = true
creeperoverhaul = true
voidz = true
dehydration = true
rocks = true
deepslatecutting = true
graveyard = true
expandeddelight = true
disenchanter = true
naturalist = true
