enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
universal_ores = true
naturalist = true
angelblockrenewed = true
mcwfences = true
farmersdelight = true
chipped = true
enchanted-vertical-slabs = true
rotten = true
overweight_farming = true
mcwwindows = true
endrem = true
betternether = true
geodes = true
brewinandchewin = true
seasons = true
customportals = true
betterend = true
another_furniture = true
earlystage = true
aquatictorches = true
ecologics = true
libraryferret = true
minecraft = true
farmersrespite = true
animal_feeding_trough = true
lootr = true
blossom = true
enhancedcelestials = true
nethersdelight = true
experiencebottler = true
numismatic-overhaul = true
moisturization = true
display_case = true
adventurez = true
creeperoverhaul = true
voidz = true
dehydration = true
creatures_from_the_snow = true
toms_storage = true
vinery = true
gofish = true
bushierflowers = true
treechop = true
expandeddelight = true
disenchanter = true
