enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
candlelight = true
universal_ores = true
mcwfences = true
seasonsextras = true
mcwroofs = true
doapi = true
mcwwindows = true
betternether = true
betterend = true
extraordinary_extra_totems = true
earlystage = true
stoneworks = true
blossom = true
sootychimneys = true
mcde = true
mythic_charms = true
dehydration = true
handcrafted = true
bakery = true
treechop = true
evenbetterarcheology = true
spell_engine = true
naturalist = true
supplementaries = true
grassoverhaul = true
minerally = true
suppsquared = true
chipped = true
endrem = true
geodes = true
extended_drawers = true
items_displayed = true
dungeonz = true
snuffles = true
customportals = true
minecraft = true
lootr = true
snifferplus = true
creeperoverhaul = true
archers = true
nethervinery = true
moisturization = true
fleshz = true
endermanoverhaul = true
beautify = true
adventurez = true
numismatic-overhaul = true
voidz = true
vinery = true
toms_storage = true
carpeted = true
illagerinvasion = true
meadow = true
bushierflowers = true
enhancedworkbenches = true
